-- DROP USER STG01;

CREATE USER STG01
-- IDENTIFIED BY <password>
;

CREATE TABLE "STG01"."AUTHORITIES"
   (	"USERNAME" NVARCHAR2(128) NOT NULL ENABLE,
	"AUTHORITY" VARCHAR2(50) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

ALTER TABLE "STG01"."AUTHORITIES" ADD CONSTRAINT "FK_AUTHORITIES_USERS" FOREIGN KEY ("USERNAME")
	  REFERENCES "STG01"."USERS" ("USERNAME") ENABLE;

CREATE UNIQUE INDEX "STG01"."IX_AUTH_USERNAME" ON "STG01"."AUTHORITIES" ("USERNAME", "AUTHORITY")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE GLOBAL TEMPORARY TABLE "STG01"."HTE_TB_IMP_DB"
   (	"DB_PARAL_DS" NUMBER(10,0),
	"DB_PARAL_ETL" NUMBER(10,0),
	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"DID" VARCHAR2(32 CHAR),
	"BVALID" VARCHAR2(255 CHAR),
	"CONF" VARCHAR2(255 CHAR),
	"DB_CONSTR" VARCHAR2(255 CHAR),
	"DB_ID_DS" VARCHAR2(255 CHAR),
	"DB_ID_ETL" VARCHAR2(255 CHAR),
	"DB_JUDGE_PRE" VARCHAR2(255 CHAR),
	"DB_JUDGE_SQL" VARCHAR2(255 CHAR),
	"DB_NAME" VARCHAR2(255 CHAR),
	"DB_PASS_DS" VARCHAR2(255 CHAR),
	"DB_PASS_ETL" VARCHAR2(255 CHAR),
	"DB_REMARK" VARCHAR2(255 CHAR),
	"DB_START" VARCHAR2(255 CHAR),
	"DB_START_TYPE" VARCHAR2(255 CHAR),
	"DB_USER_DS" VARCHAR2(255 CHAR),
	"DB_USER_ETL" VARCHAR2(255 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS ;

CREATE UNIQUE INDEX "STG01"."SYS_C0059876" ON "STG01"."HTE_TB_IMP_DB" ("RN_") ;
;

CREATE GLOBAL TEMPORARY TABLE "STG01"."HTE_TB_IMP_ETL"
   (	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"END_TIME" TIMESTAMP (6),
	"REALTIME_INTERVAL" NUMBER(19,0),
	"RETRY_CNT" NUMBER(19,0),
	"RUNTIME" NUMBER(19,0),
	"RUNTIME_ADD" NUMBER(19,0),
	"START_TIME" TIMESTAMP (6),
	"AFTER_RETRY_FIXED" VARCHAR2(255 CHAR),
	"AFTER_RETRY_PNTYPE" VARCHAR2(255 CHAR),
	"BCREATE" VARCHAR2(255 CHAR),
	"BPREVIEW" VARCHAR2(255 CHAR),
	"BTDH" VARCHAR2(255 CHAR),
	"BUPDATE" VARCHAR2(255 CHAR),
	"DEST_PART_KIND" VARCHAR2(255 CHAR),
	"DEST_TABLENAME" VARCHAR2(255 CHAR),
	"ETL_KIND" VARCHAR2(255 CHAR),
	"FLAG" VARCHAR2(255 CHAR),
	"PARAM_SOU" VARCHAR2(255 CHAR),
	"REALTIME_FIXED" VARCHAR2(255 CHAR),
	"REALTIME_INTERVAL_RANGE" VARCHAR2(255 CHAR),
	"REALTIME_SOU_FILTER" VARCHAR2(255 CHAR),
	"REALTIME_SOU_OWNER" VARCHAR2(255 CHAR),
	"REALTIME_TASKGROUP" VARCHAR2(255 CHAR),
	"REMARK" VARCHAR2(255 CHAR),
	"SOU_FILTER" VARCHAR2(255 CHAR),
	"SOU_OWNER" VARCHAR2(255 CHAR),
	"SOU_SPLIT" VARCHAR2(255 CHAR),
	"SOU_SYSID" VARCHAR2(255 CHAR),
	"SOU_TABLENAME" VARCHAR2(255 CHAR),
	"TID" VARCHAR2(255 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS ;

CREATE UNIQUE INDEX "STG01"."SYS_C0023777" ON "STG01"."HTE_TB_IMP_ETL" ("RN_") ;
;

CREATE TABLE "STG01"."TB_CI_DEPLOY"
   (	"DEP_ID" VARCHAR2(32),
	"PROJ_NAME" VARCHAR2(200),
	"FILE_PATH" VARCHAR2(200),
	"FILE_NAME" VARCHAR2(200),
	"FILE_CONTENT" CLOB,
	"FILE_MD5" VARCHAR2(100),
	"COMMIT_USER" VARCHAR2(500),
	"UPDT_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 76742656 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"
 LOB ("FILE_CONTENT") STORE AS BASICFILE (
  TABLESPACE "T_STG01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

COMMENT ON COLUMN STG01.TB_CI_DEPLOY.DEP_ID IS '唯一标识，同一次提交的所有文件，用相同的值';
COMMENT ON COLUMN STG01.TB_CI_DEPLOY.PROJ_NAME IS '项目名称';
COMMENT ON COLUMN STG01.TB_CI_DEPLOY.FILE_PATH IS '文件路径';
COMMENT ON COLUMN STG01.TB_CI_DEPLOY.FILE_NAME IS '完整的文件名，包含扩展名';
COMMENT ON COLUMN STG01.TB_CI_DEPLOY.FILE_CONTENT IS '文件内容，不做拆分，原样存放';
COMMENT ON COLUMN STG01.TB_CI_DEPLOY.FILE_MD5 IS '文件内容MD5';
COMMENT ON COLUMN STG01.TB_CI_DEPLOY.COMMIT_USER IS '提交人';

CREATE TABLE "STG01"."TB_DICT"
   (	"DICT_CODE" VARCHAR2(4),
	"DICT_NAME" VARCHAR2(255),
	"DICT_CLASS" VARCHAR2(2000),
	"REMARK" VARCHAR2(2000),
	 CONSTRAINT "PK_TB_DICT" PRIMARY KEY ("DICT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."PK_TB_DICT" ON "STG01"."TB_DICT" ("DICT_CODE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE TABLE "STG01"."TB_DICTIONARY"
   (	"ENTRY_CODE" VARCHAR2(4),
	"ENTRY_VALUE" VARCHAR2(255),
	"ENTRY_CONTENT" VARCHAR2(2000),
	"REMARK" VARCHAR2(4000),
	 CONSTRAINT "PK_TB_DICTIONARY" PRIMARY KEY ("ENTRY_CODE", "ENTRY_VALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."PK_TB_DICTIONARY" ON "STG01"."TB_DICTIONARY" ("ENTRY_CODE", "ENTRY_VALUE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE TABLE "STG01"."TB_IMP_CHK"
   (	"CHK_KIND" VARCHAR2(1000),
	"CHK_NAME" VARCHAR2(1000),
	"CHK_CONTENT" VARCHAR2(4000),
	"UPDT_DATE" DATE DEFAULT sysdate,
	"CHK_MOBILE" VARCHAR2(500),
	"CHK_SENDTYPE" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE TABLE "STG01"."TB_IMP_CHK_INF"
   (	"CHK_IDX" VARCHAR2(255),
	"CHK_SENDTYPE" VARCHAR2(4000),
	"CHK_MOBILE" VARCHAR2(4000),
	"BPNTYPE" NUMBER,
	"CHK_KIND" VARCHAR2(4000),
	"CHK_SQL" VARCHAR2(4000),
	"START_TIME" TIMESTAMP (6),
	"END_TIME" TIMESTAMP (6),
	"ENGINE" VARCHAR2(32)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE TABLE "STG01"."TB_IMP_DB"
   (	"DB_NAME" VARCHAR2(200),
	"DB_CONSTR" VARCHAR2(500),
	"DB_ID_ETL" VARCHAR2(64),
	"DB_USER_ETL" VARCHAR2(64),
	"DB_PASS_ETL" VARCHAR2(64),
	"DB_PARAL_ETL" NUMBER(*,0),
	"DB_ID_DS" VARCHAR2(64),
	"DB_USER_DS" VARCHAR2(64),
	"DB_PASS_DS" VARCHAR2(64),
	"DB_PARAL_DS" NUMBER(*,0),
	"DB_START" VARCHAR2(32),
	"DB_START_TYPE" CHAR(1),
	"DB_JUDGE_SQL" VARCHAR2(4000),
	"DB_JUDGE_PRE" VARCHAR2(4000),
	"DB_REMARK" CLOB,
	"DID" VARCHAR2(32) DEFAULT sys_guid(),
	"BVALID" CHAR(1) DEFAULT 'Y',
	"CONF" VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"
 LOB ("DB_REMARK") STORE AS BASICFILE (
  TABLESPACE "T_STG01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

COMMENT ON COLUMN STG01.TB_IMP_DB.DB_NAME IS '数据库名称';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_CONSTR IS '数据库连接串';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_ID_ETL IS '数据库在采集时的编号';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_USER_ETL IS '数据库在采集时的用户';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_PASS_ETL IS '数据库在采集时的密码';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_PARAL_ETL IS '数据库在采集时的并发数';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_ID_DS IS '数据库在数据服务时的编号';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_USER_DS IS '数据库在数据服务时的用户';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_PASS_DS IS '数据库在数据服务时的密码';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_PARAL_DS IS '数据库在数据服务时的并发数';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_START IS '数据库定时启动时间点';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_START_TYPE IS '数据库定时启动类型,pn_type';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_JUDGE_SQL IS '判断标志获取标志脚本';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_JUDGE_PRE IS '标志符合条件后的前置脚本';
COMMENT ON COLUMN STG01.TB_IMP_DB.DB_REMARK IS '系统备注信息';
COMMENT ON COLUMN STG01.TB_IMP_DB.BVALID IS '是否有效';
COMMENT ON COLUMN STG01.TB_IMP_DB.CONF IS '额外的配置信息';

CREATE TABLE "STG01"."TB_IMP_DS2"
   (	"TASK_GROUP" VARCHAR2(32) NOT NULL ENABLE,
	"DEST_SYSID" VARCHAR2(32) NOT NULL ENABLE,
	"DEST_OWNER" VARCHAR2(32),
	"FLAG" CHAR(1) DEFAULT 'N',
	"PARAM_SOU" CHAR(1) DEFAULT 'C',
	"RETRY_CNT" NUMBER(*,0) DEFAULT 3,
	"START_TIME" DATE DEFAULT sysdate,
	"END_TIME" DATE DEFAULT sysdate,
	"DS_ID" VARCHAR2(32) DEFAULT sys_guid() NOT NULL ENABLE,
	"PRE_SQL" VARCHAR2(2000) DEFAULT 'T',
	"POST_SQL" VARCHAR2(4000),
	"COL_MAP" VARCHAR2(2000),
	"PARAL_NUM" NUMBER(*,0) DEFAULT 1,
	"BUPDATE" CHAR(1) DEFAULT 'Y',
	"RUNTIME" NUMBER(10,0) DEFAULT 999,
	"PRE_SH" VARCHAR2(4000),
	"POST_SH" VARCHAR2(4000),
	"MAX_RUNTIME" NUMBER(*,0) DEFAULT 3600,
	"RUN_FREQ" VARCHAR2(3) DEFAULT 'D',
	"PN_FIXED" VARCHAR2(200),
	"PN_INTERVAL" NUMBER(5,0) DEFAULT null,
	"PN_RANGE" VARCHAR2(32),
	"PN_TYPE" CHAR(1),
	"REMARK" VARCHAR2(2000),
	 CONSTRAINT "PK_TB_IMP_DS2" PRIMARY KEY ("DS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE,
	 CONSTRAINT "UK_TB_IMP_DS2" UNIQUE ("DEST_SYSID", "TASK_GROUP", "RUN_FREQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."UK_TB_IMP_DS2" ON "STG01"."TB_IMP_DS2" ("DEST_SYSID", "TASK_GROUP", "RUN_FREQ")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
  CREATE UNIQUE INDEX "STG01"."PK_TB_IMP_DS2" ON "STG01"."TB_IMP_DS2" ("DS_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

COMMENT ON COLUMN STG01.TB_IMP_DS2.PARAL_NUM IS '执行并发数';
COMMENT ON COLUMN STG01.TB_IMP_DS2.MAX_RUNTIME IS '允许最长耗时';
COMMENT ON COLUMN STG01.TB_IMP_DS2.RUN_FREQ IS '运行频率，周期(D天,W周,M月,Q季度,Y年度)';

CREATE TABLE "STG01"."TB_IMP_DS2_TBLS"
   (	"DS_ID" VARCHAR2(32) NOT NULL ENABLE,
	"SOU_ISHDP" CHAR(1) DEFAULT 1,
	"SOU_TABLE" VARCHAR2(4000) NOT NULL ENABLE,
	"SOU_FILTER" VARCHAR2(1000),
	"DEST_OWNER" VARCHAR2(32),
	"DEST_TABLENAME" VARCHAR2(128) NOT NULL ENABLE,
	"FLAG" CHAR(1) DEFAULT 'N',
	"START_TIME" DATE DEFAULT sysdate,
	"END_TIME" DATE DEFAULT sysdate,
	"TBL_ID" VARCHAR2(32) DEFAULT sys_guid(),
	"PRE_SQL" VARCHAR2(2000),
	"COL_MAP" VARCHAR2(4000),
	"POST_SQL" VARCHAR2(2000),
	"MAX_RUNTIME" NUMBER(*,0),
	 CONSTRAINT "PK_TB_IMP_DS2_TBLS" PRIMARY KEY ("TBL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE,
	 CONSTRAINT "UK_TB_IMP_DS2_TBLS" UNIQUE ("DS_ID", "DEST_OWNER", "DEST_TABLENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."UK_TB_IMP_DS2_TBLS" ON "STG01"."TB_IMP_DS2_TBLS" ("DS_ID", "DEST_OWNER", "DEST_TABLENAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
  CREATE UNIQUE INDEX "STG01"."PK_TB_IMP_DS2_TBLS" ON "STG01"."TB_IMP_DS2_TBLS" ("TBL_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

COMMENT ON COLUMN STG01.TB_IMP_DS2_TBLS.SOU_ISHDP IS '是否从hdp推送';
COMMENT ON COLUMN STG01.TB_IMP_DS2_TBLS.SOU_FILTER IS '源筛选条件';
COMMENT ON COLUMN STG01.TB_IMP_DS2_TBLS.MAX_RUNTIME IS '允许最长耗时';

CREATE TABLE "STG01"."TB_IMP_ETL"
   (	"SOU_SYSID" VARCHAR2(32) NOT NULL ENABLE,
	"SOU_OWNER" VARCHAR2(32) NOT NULL ENABLE,
	"SOU_TABLENAME" VARCHAR2(64) NOT NULL ENABLE,
	"SOU_FILTER" VARCHAR2(2000) DEFAULT '1=1' NOT NULL ENABLE,
	"DEST_TABLENAME" VARCHAR2(64) NOT NULL ENABLE,
	"DEST_PART_KIND" CHAR(1) DEFAULT 'D',
	"FLAG" CHAR(1) DEFAULT 'W',
	"PARAM_SOU" CHAR(1) DEFAULT 'C',
	"BUPDATE" CHAR(1) DEFAULT 'Y',
	"BCREATE" CHAR(1) DEFAULT 'Y',
	"RETRY_CNT" NUMBER(1,0) DEFAULT 3,
	"START_TIME" DATE DEFAULT sysdate,
	"END_TIME" DATE DEFAULT sysdate,
	"RUNTIME" NUMBER(10,0) DEFAULT 2000,
	"TID" VARCHAR2(32) DEFAULT sys_guid() NOT NULL ENABLE,
	"SOU_SPLIT" VARCHAR2(32),
	"REMARK" CLOB,
	"ETL_KIND" CHAR(1) DEFAULT 'A',
	"BPREVIEW" CHAR(1) DEFAULT 'N',
	"REALTIME_INTERVAL" NUMBER(4,0) DEFAULT 0,
	"REALTIME_TASKGROUP" VARCHAR2(32),
	"REALTIME_SOU_OWNER" VARCHAR2(32),
	"REALTIME_FIXED" VARCHAR2(32),
	"REALTIME_SOU_FILTER" VARCHAR2(2000),
	"REALTIME_INTERVAL_RANGE" VARCHAR2(100),
	"AFTER_RETRY_FIXED" VARCHAR2(32),
	"AFTER_RETRY_PNTYPE" CHAR(1),
	"BTDH" CHAR(1) DEFAULT 'N',
	"RUNTIME_ADD" NUMBER(10,0) DEFAULT 0,
	 CONSTRAINT "PK_TB_IMP_ETL" PRIMARY KEY ("TID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE,
	 CONSTRAINT "UK_TB_IMP_ETL" UNIQUE ("SOU_SYSID", "DEST_TABLENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 393216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"
 LOB ("REMARK") STORE AS BASICFILE (
  TABLESPACE "T_STG01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "STG01"."SYS_IL0000075601C00017$$" ON "STG01"."TB_IMP_ETL" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "STG01"."UK_TB_IMP_ETL" ON "STG01"."TB_IMP_ETL" ("SOU_SYSID", "DEST_TABLENAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 393216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
  CREATE UNIQUE INDEX "STG01"."PK_TB_IMP_ETL" ON "STG01"."TB_IMP_ETL" ("TID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

COMMENT ON COLUMN STG01.TB_IMP_ETL.SOU_SYSID IS '源系统编号';
COMMENT ON COLUMN STG01.TB_IMP_ETL.SOU_OWNER IS '源用户';
COMMENT ON COLUMN STG01.TB_IMP_ETL.SOU_TABLENAME IS '源表';
COMMENT ON COLUMN STG01.TB_IMP_ETL.SOU_FILTER IS '源筛选条件';
COMMENT ON COLUMN STG01.TB_IMP_ETL.DEST_TABLENAME IS '目标表名';
COMMENT ON COLUMN STG01.TB_IMP_ETL.DEST_PART_KIND IS '入库规则';
COMMENT ON COLUMN STG01.TB_IMP_ETL.FLAG IS '运行状态';
COMMENT ON COLUMN STG01.TB_IMP_ETL.PARAM_SOU IS '参数组';
COMMENT ON COLUMN STG01.TB_IMP_ETL.BUPDATE IS '是否更新表的元数据信息';
COMMENT ON COLUMN STG01.TB_IMP_ETL.BCREATE IS '是否在hadoop上建表';
COMMENT ON COLUMN STG01.TB_IMP_ETL.RETRY_CNT IS '重试次数';
COMMENT ON COLUMN STG01.TB_IMP_ETL.START_TIME IS '采集开始时间';
COMMENT ON COLUMN STG01.TB_IMP_ETL.END_TIME IS '采集结束时间';
COMMENT ON COLUMN STG01.TB_IMP_ETL.ETL_KIND IS '该表目前的采集模式:A盘后采集,R实时采集,默认A';
COMMENT ON COLUMN STG01.TB_IMP_ETL.BPREVIEW IS '是否推送至预发布环境';
COMMENT ON COLUMN STG01.TB_IMP_ETL.REALTIME_INTERVAL IS '实时频率（分钟），0为不开启实时';
COMMENT ON COLUMN STG01.TB_IMP_ETL.REALTIME_TASKGROUP IS '实时任务的任务组，盘后采集的任务组为数据源编号';
COMMENT ON COLUMN STG01.TB_IMP_ETL.REALTIME_SOU_OWNER IS '实时采集时的源表用户,为空取sou_owner';
COMMENT ON COLUMN STG01.TB_IMP_ETL.REALTIME_FIXED IS '实时定点采集，非间隔';
COMMENT ON COLUMN STG01.TB_IMP_ETL.REALTIME_SOU_FILTER IS '实时采集时的源表筛选条件';
COMMENT ON COLUMN STG01.TB_IMP_ETL.REALTIME_INTERVAL_RANGE IS '实时频率的时间范围';
COMMENT ON COLUMN STG01.TB_IMP_ETL.AFTER_RETRY_FIXED IS '盘后任务重采定时';
COMMENT ON COLUMN STG01.TB_IMP_ETL.AFTER_RETRY_PNTYPE IS '盘后任务重采计划';
COMMENT ON COLUMN STG01.TB_IMP_ETL.BTDH IS '是否推送至星环hadoop';
COMMENT ON COLUMN STG01.TB_IMP_ETL.RUNTIME_ADD IS '运行时间增加，仅用于任务提前执行';

CREATE TABLE "STG01"."TB_IMP_ETL_SOUTAB"
   (	"SOU_DB_CONN" VARCHAR2(64) NOT NULL ENABLE,
	"OWNER" VARCHAR2(64) NOT NULL ENABLE,
	"TABLE_NAME" VARCHAR2(64) NOT NULL ENABLE,
	"COLUMN_NAME" VARCHAR2(64) NOT NULL ENABLE,
	"DATA_TYPE" VARCHAR2(64),
	"DATA_LENGTH" NUMBER(10,0),
	"DATA_PRECISION" NUMBER(10,0),
	"DATA_SCALE" NUMBER(10,0),
	"COLUMN_ID" NUMBER(10,0),
	"TABLE_TYPE" VARCHAR2(32),
	"TAB_COMMENT" VARCHAR2(2000),
	"COL_COMMENT" VARCHAR2(2000),
	"DW_CLT_DATE" DATE DEFAULT sysdate,
	 CONSTRAINT "PK_TB_IMP_ETL_SOUTAB" PRIMARY KEY ("SOU_DB_CONN", "OWNER", "TABLE_NAME", "COLUMN_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 25165824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 175702016 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."PK_TB_IMP_ETL_SOUTAB" ON "STG01"."TB_IMP_ETL_SOUTAB" ("SOU_DB_CONN", "OWNER", "TABLE_NAME", "COLUMN_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 25165824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE TABLE "STG01"."TB_IMP_ETL_TBLS"
   (	"DB_ID" NUMBER(*,0),
	"DB_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"DB_LOCATION" VARCHAR2(2000),
	"TBL_ID" NUMBER(*,0),
	"TBL_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"TBL_TYPE" VARCHAR2(255),
	"TBL_LOCATION" VARCHAR2(2000),
	"CD_ID" NUMBER(*,0),
	"COL_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"COL_TYPE" VARCHAR2(500),
	"COL_COMMENT" VARCHAR2(2000),
	"COL_IDX" NUMBER(*,0),
	"TBL_COMMENT" VARCHAR2(2000),
	 CONSTRAINT "PK_TB_IMP_ETL_TBLS" PRIMARY KEY ("DB_NAME", "TBL_NAME", "COL_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 37748736 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 78315520 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."PK_TB_IMP_ETL_TBLS" ON "STG01"."TB_IMP_ETL_TBLS" ("DB_NAME", "TBL_NAME", "COL_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 37748736 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

COMMENT ON TABLE STG01.TB_IMP_ETL_TBLS IS 'HIVE的表结构信息';
COMMENT ON COLUMN STG01.TB_IMP_ETL_TBLS.DB_NAME IS '数据库名、用户';
COMMENT ON COLUMN STG01.TB_IMP_ETL_TBLS.DB_LOCATION IS '数据库所在HDFS地址';
COMMENT ON COLUMN STG01.TB_IMP_ETL_TBLS.TBL_NAME IS '表名';
COMMENT ON COLUMN STG01.TB_IMP_ETL_TBLS.TBL_TYPE IS '表类型（管理表、外部表）';
COMMENT ON COLUMN STG01.TB_IMP_ETL_TBLS.TBL_LOCATION IS '表所在HDFS地址';
COMMENT ON COLUMN STG01.TB_IMP_ETL_TBLS.COL_NAME IS '字段名';
COMMENT ON COLUMN STG01.TB_IMP_ETL_TBLS.COL_TYPE IS '字段类型';
COMMENT ON COLUMN STG01.TB_IMP_ETL_TBLS.COL_COMMENT IS '字段备注';
COMMENT ON COLUMN STG01.TB_IMP_ETL_TBLS.COL_IDX IS '字段顺序';
COMMENT ON COLUMN STG01.TB_IMP_ETL_TBLS.TBL_COMMENT IS '表注释';

CREATE TABLE "STG01"."TB_IMP_ETL_TBLS_TMP"
   (	"DB_ID" NUMBER(19,0),
	"DB_NAME" VARCHAR2(255),
	"DB_LOCATION" VARCHAR2(255),
	"TBL_ID" NUMBER(19,0),
	"TBL_NAME" VARCHAR2(255),
	"TBL_TYPE" VARCHAR2(255),
	"TBL_LOCATION" VARCHAR2(255),
	"CD_ID" NUMBER(19,0),
	"COL_NAME" VARCHAR2(255),
	"COL_TYPE" VARCHAR2(500),
	"COL_COMMENT" VARCHAR2(2000),
	"COL_IDX" NUMBER(19,0),
	"TBL_COMMENT" VARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 70254592 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE TABLE "STG01"."TB_IMP_FLAG"
   (	"TRADEDATE" NUMBER(10,0),
	"KIND" VARCHAR2(32) NOT NULL ENABLE,
	"FID" VARCHAR2(32) NOT NULL ENABLE,
	"FVAL" VARCHAR2(32),
	"DW_CLT_DATE" DATE DEFAULT sysdate NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE TABLE "STG01"."TB_IMP_JOUR"
   (	"KIND" VARCHAR2(32),
	"TRADE_DATE" NUMBER(10,0),
	"STATUS" VARCHAR2(32),
	"KEY_ID" VARCHAR2(4000),
	"REMARK" VARCHAR2(4000),
	"UPDT_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 189005824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE TABLE "STG01"."TB_IMP_PARAM0"
   (	"PARAM_SOU" CHAR(1),
	"PARAM_KIND_0" VARCHAR2(255),
	"PARAM_KIND" VARCHAR2(258),
	"PARAM_NAME" VARCHAR2(2000),
	"PARAM_REMARK" VARCHAR2(4000),
	"PARAM_VALUE" VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."TB_IMP_PARAM0_PARAM_SOU_IDX" ON "STG01"."TB_IMP_PARAM0" ("PARAM_SOU", "PARAM_KIND_0")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

COMMENT ON TABLE STG01.TB_IMP_PARAM0 IS '日期参数文件基表';

CREATE TABLE "STG01"."TB_IMP_PLAN"
   (	"PN_TYPE" CHAR(1),
	"PN_FIXED" VARCHAR2(200),
	"PN_INTERVAL" NUMBER(5,0),
	"PN_RANGE" VARCHAR2(32),
	"PN_ID" VARCHAR2(32) DEFAULT sys_guid() NOT NULL ENABLE,
	"FLAG" CHAR(1) DEFAULT 'N',
	"START_TIME" DATE DEFAULT sysdate,
	"END_TIME" DATE DEFAULT sysdate,
	"BEXIT" CHAR(1) DEFAULT 'Y',
	"RUNTIME" NUMBER(10,0),
	 CONSTRAINT "PK_IMP_PLAN" PRIMARY KEY ("PN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."PK_IMP_PLAN" ON "STG01"."TB_IMP_PLAN" ("PN_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

COMMENT ON COLUMN STG01.TB_IMP_PLAN.PN_TYPE IS '定时计划类型，参考参数1064';
COMMENT ON COLUMN STG01.TB_IMP_PLAN.PN_FIXED IS '定点时间';
COMMENT ON COLUMN STG01.TB_IMP_PLAN.PN_INTERVAL IS '轮询间隔';
COMMENT ON COLUMN STG01.TB_IMP_PLAN.PN_RANGE IS '轮询时间区间';
COMMENT ON COLUMN STG01.TB_IMP_PLAN.BEXIT IS '是否跳过切日时间段';

CREATE TABLE "STG01"."TB_IMP_SP"
   (	"SP_OWNER" VARCHAR2(255) NOT NULL ENABLE,
	"SP_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"SP_ID" VARCHAR2(32) DEFAULT sys_guid() NOT NULL ENABLE,
	"FLAG" CHAR(1) DEFAULT 'N',
	"RUN_FREQ" VARCHAR2(3) DEFAULT 'D',
	"START_TIME" DATE DEFAULT sysdate,
	"END_TIME" DATE DEFAULT sysdate,
	"RETRY_CNT" NUMBER(2,0) DEFAULT 3,
	"RUNTIME" NUMBER(10,0) DEFAULT 999,
	"TASK_GROUP" VARCHAR2(128),
	"PARAM_SOU" CHAR(1) DEFAULT 'C',
	"REMARK" CLOB,
	"REALTIME_TASKGROUP" VARCHAR2(32),
	"PN_TYPE" CHAR(1),
	"PN_FIXED" VARCHAR2(200),
	"PN_INTERVAL" NUMBER(5,0),
	"PN_RANGE" VARCHAR2(32),
	 CONSTRAINT "PK_IMP_SP_ID" PRIMARY KEY ("SP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE,
	 CONSTRAINT "PK_IMP_SP_NAME" UNIQUE ("SP_OWNER", "SP_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"
 LOB ("REMARK") STORE AS BASICFILE (
  TABLESPACE "T_STG01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "STG01"."SYS_IL0000075615C00012$$" ON "STG01"."TB_IMP_SP" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "STG01"."PK_IMP_SP_NAME" ON "STG01"."TB_IMP_SP" ("SP_OWNER", "SP_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
  CREATE UNIQUE INDEX "STG01"."PK_IMP_SP_ID" ON "STG01"."TB_IMP_SP" ("SP_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

COMMENT ON TABLE STG01.TB_IMP_SP IS 'HADOOP_SP的配置主表';
COMMENT ON COLUMN STG01.TB_IMP_SP.SP_OWNER IS 'SP用户';
COMMENT ON COLUMN STG01.TB_IMP_SP.SP_NAME IS 'SP名称';
COMMENT ON COLUMN STG01.TB_IMP_SP.SP_ID IS 'SP的主键，自动生成，唯一性';
COMMENT ON COLUMN STG01.TB_IMP_SP.FLAG IS '运行状态';
COMMENT ON COLUMN STG01.TB_IMP_SP.RUN_FREQ IS '运行频率，周期(D天,W周,M月,Q季度,Y年度)';
COMMENT ON COLUMN STG01.TB_IMP_SP.START_TIME IS '运行开始时间';
COMMENT ON COLUMN STG01.TB_IMP_SP.END_TIME IS '运行结束时间';
COMMENT ON COLUMN STG01.TB_IMP_SP.RETRY_CNT IS '错误重试次数';
COMMENT ON COLUMN STG01.TB_IMP_SP.RUNTIME IS '任务运行时间，用来并发排序';
COMMENT ON COLUMN STG01.TB_IMP_SP.TASK_GROUP IS '所属任务组，用于调起后续工作流';
COMMENT ON COLUMN STG01.TB_IMP_SP.PARAM_SOU IS '参数文件组（L昨日，C当日，N下日）';
COMMENT ON COLUMN STG01.TB_IMP_SP.REMARK IS '备注信息';
COMMENT ON COLUMN STG01.TB_IMP_SP.REALTIME_TASKGROUP IS '前置采集任务组(专用了等待实时的采集任务组)';
COMMENT ON COLUMN STG01.TB_IMP_SP.PN_TYPE IS '计划类型';
COMMENT ON COLUMN STG01.TB_IMP_SP.PN_FIXED IS '计划定点时间 ';
COMMENT ON COLUMN STG01.TB_IMP_SP.PN_INTERVAL IS '计划间隔时间';
COMMENT ON COLUMN STG01.TB_IMP_SP.PN_RANGE IS '计划间隔时间范围';

CREATE TABLE "STG01"."TB_IMP_SP_COM"
   (	"SP_ID" VARCHAR2(32) NOT NULL ENABLE,
	"COM_IDX" NUMBER(*,0) NOT NULL ENABLE,
	"COM_KIND" VARCHAR2(10),
	"COM_TEXT" CLOB,
	"START_TIME" DATE DEFAULT sysdate,
	"END_TIME" DATE DEFAULT sysdate,
	"COM_ID" VARCHAR2(32) DEFAULT sys_guid() NOT NULL ENABLE,
	"FLAG" VARCHAR2(1) DEFAULT 'N',
	 CONSTRAINT "PK_IMP_SP_COM" PRIMARY KEY ("COM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE,
	 CONSTRAINT "UK_IMP_SP_COM" UNIQUE ("SP_ID", "COM_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 50724864 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"
 LOB ("COM_TEXT") STORE AS BASICFILE (
  TABLESPACE "T_STG01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "STG01"."SYS_IL0000075610C00004$$" ON "STG01"."TB_IMP_SP_COM" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "STG01"."UK_IMP_SP_COM" ON "STG01"."TB_IMP_SP_COM" ("SP_ID", "COM_IDX")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
  CREATE UNIQUE INDEX "STG01"."PK_IMP_SP_COM" ON "STG01"."TB_IMP_SP_COM" ("COM_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

COMMENT ON TABLE STG01.TB_IMP_SP_COM IS 'HADOOP_SP的运行脚本（作为主表的附属表）';
COMMENT ON COLUMN STG01.TB_IMP_SP_COM.SP_ID IS '主表的SP_ID';
COMMENT ON COLUMN STG01.TB_IMP_SP_COM.COM_IDX IS '命令执行顺序';
COMMENT ON COLUMN STG01.TB_IMP_SP_COM.COM_KIND IS '命令类型：hive、presto、spark-sql、shell、spark，参照runcmds.sh的runkind';
COMMENT ON COLUMN STG01.TB_IMP_SP_COM.COM_TEXT IS '命令正文';
COMMENT ON COLUMN STG01.TB_IMP_SP_COM.START_TIME IS '开始时间';
COMMENT ON COLUMN STG01.TB_IMP_SP_COM.END_TIME IS '结束时间';
COMMENT ON COLUMN STG01.TB_IMP_SP_COM.FLAG IS '状态(包含生成脚本状态、执行情况)';

CREATE TABLE "STG01"."TB_IMP_SP_NEEDALL"
   (	"SP_ID" VARCHAR2(32) NOT NULL ENABLE,
	"NEED_SOU" VARCHAR2(4000),
	"NEED_SP" VARCHAR2(4000),
	"SP_ALLTABS" VARCHAR2(4000),
	"SP_DEST" VARCHAR2(4000),
	"THROUGH_NEED_SOU" VARCHAR2(4000),
	"THROUGH_NEED_SP" CLOB,
	 CONSTRAINT "PK_TB_IMP_SP_NEEDALL" PRIMARY KEY ("SP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"
 LOB ("THROUGH_NEED_SP") STORE AS BASICFILE (
  TABLESPACE "T_STG01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "STG01"."SYS_IL0000075606C00007$$" ON "STG01"."TB_IMP_SP_NEEDALL" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "STG01"."PK_TB_IMP_SP_NEEDALL" ON "STG01"."TB_IMP_SP_NEEDALL" ("SP_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

COMMENT ON COLUMN STG01.TB_IMP_SP_NEEDALL.NEED_SOU IS '前置数据源';
COMMENT ON COLUMN STG01.TB_IMP_SP_NEEDALL.NEED_SP IS '前置SP';
COMMENT ON COLUMN STG01.TB_IMP_SP_NEEDALL.SP_ALLTABS IS '所有前置表';
COMMENT ON COLUMN STG01.TB_IMP_SP_NEEDALL.SP_DEST IS 'SP生成表';
COMMENT ON COLUMN STG01.TB_IMP_SP_NEEDALL.THROUGH_NEED_SOU IS '穿透后所有前置数据源';
COMMENT ON COLUMN STG01.TB_IMP_SP_NEEDALL.THROUGH_NEED_SP IS '穿透后所有前置SP';

CREATE TABLE "STG01"."TB_IMP_SP_NEEDTAB"
   (	"SP_ID" VARCHAR2(32),
	"TABLE_NAME" VARCHAR2(200),
	"UPDT" DATE DEFAULT sysdate,
	"KIND" VARCHAR2(32) DEFAULT 'ALL'
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE TABLE "STG01"."TB_IMP_TBL_HDP"
   (	"TID" VARCHAR2(32) NOT NULL ENABLE,
	"HIVE_OWNER" VARCHAR2(35),
	"HIVE_TABLENAME" VARCHAR2(64) NOT NULL ENABLE,
	"COL_NAME" VARCHAR2(255),
	"COL_TYPE_FULL" VARCHAR2(500),
	"COL_TYPE" VARCHAR2(2000),
	"COL_PRECISION" NUMBER(*,0),
	"COL_SCALE" NUMBER(*,0),
	"COL_IDX" NUMBER(*,0),
	"TBL_COMMENT" VARCHAR2(4000),
	"COL_COMMENT" VARCHAR2(4000),
	"UPDT_DATE" DATE DEFAULT sysdate,
	"CD_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4294967296 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."UK_TB_IMP_TBL_HDP" ON "STG01"."TB_IMP_TBL_HDP" ("TID", "COL_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 12582912 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
  CREATE INDEX "STG01"."IDX_TB_IMP_TBL_HDP" ON "STG01"."TB_IMP_TBL_HDP" ("TID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 32505856 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE TABLE "STG01"."TB_IMP_TBL_SOU"
   (	"TID" VARCHAR2(32) NOT NULL ENABLE,
	"SOU_DB_CONN" VARCHAR2(35),
	"SOU_OWNER" VARCHAR2(32),
	"SOU_TABLENAME" VARCHAR2(64),
	"COLUMN_NAME_ORIG" VARCHAR2(64),
	"COLUMN_NAME" VARCHAR2(71),
	"COLUMN_ID" NUMBER(10,0),
	"DATA_TYPE" VARCHAR2(64),
	"DATA_LENGTH" NUMBER(10,0),
	"DATA_PRECISION" NUMBER,
	"DATA_SCALE" NUMBER,
	"TBL_COMMENT" VARCHAR2(4000),
	"COL_COMMENT" VARCHAR2(4000),
	"DEST_TYPE" VARCHAR2(2000),
	"DEST_TYPE_FULL" VARCHAR2(2083),
	"UPDT_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4294967296 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."UK_TB_IMP_TBL_SOU" ON "STG01"."TB_IMP_TBL_SOU" ("TID", "COLUMN_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 11534336 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
  CREATE INDEX "STG01"."IDX_TB_IMP_TBL_SOU" ON "STG01"."TB_IMP_TBL_SOU" ("TID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 28311552 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;

CREATE TABLE "STG01"."TB_MSG"
   (	"MID" VARCHAR2(32) DEFAULT sys_guid() NOT NULL ENABLE,
	"PHONE" VARCHAR2(255) NOT NULL ENABLE,
	"MSG" VARCHAR2(500) NOT NULL ENABLE,
	"DW_CLT_DATE" DATE DEFAULT sysdate NOT NULL ENABLE,
	"BSMS" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"BKK" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"BCALL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	 CONSTRAINT "PK_TB_MSG" PRIMARY KEY ("MID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."PK_TB_MSG" ON "STG01"."TB_MSG" ("MID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

COMMENT ON TABLE STG01.TB_MSG IS '数据中心消息提醒总表';
COMMENT ON COLUMN STG01.TB_MSG.MID IS '自动生成，无需理会';
COMMENT ON COLUMN STG01.TB_MSG.PHONE IS '接收人号码或者其他唯一标识，用逗号分隔';
COMMENT ON COLUMN STG01.TB_MSG.MSG IS '消息内容';
COMMENT ON COLUMN STG01.TB_MSG.DW_CLT_DATE IS '消息生成的时间，自动生成';
COMMENT ON COLUMN STG01.TB_MSG.BSMS IS '是否发送短信，发送成功后置为y';
COMMENT ON COLUMN STG01.TB_MSG.BKK IS '是否发送KK，发送成功后置为y';
COMMENT ON COLUMN STG01.TB_MSG.BCALL IS '是否拨打语音，拨打成功后置为y';

CREATE GLOBAL TEMPORARY TABLE "STG01"."TMP_CI_DEPLOY_ADD"
   (	"SP_ID" VARCHAR2(32),
	"SP_OWNER" VARCHAR2(100),
	"SP_NAME" VARCHAR2(100),
	"ADD_KIND" NUMBER(1,0) DEFAULT 0,
	"COM_TEXT" CLOB
   ) ON COMMIT DELETE ROWS ;
;

CREATE GLOBAL TEMPORARY TABLE "STG01"."TMP_IMP"
   (	"KIND" VARCHAR2(32),
	"PKID" VARCHAR2(256),
	"STR1" VARCHAR2(1000),
	"STR2" VARCHAR2(1000),
	"STR3" VARCHAR2(1000)
   ) ON COMMIT DELETE ROWS ;
;

CREATE GLOBAL TEMPORARY TABLE "STG01"."TMP_IMP_SP_NEEDTAB"
   (	"SP_ID" VARCHAR2(32),
	"SP_NAME" VARCHAR2(1000),
	"COM_TEXT" CLOB
   ) ON COMMIT DELETE ROWS ;
;

CREATE TABLE "STG01"."USERS"
   (	"USERNAME" NVARCHAR2(128),
	"PASSWORD" NVARCHAR2(128) NOT NULL ENABLE,
	"ENABLED" CHAR(1) NOT NULL ENABLE,
	 PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;

CREATE UNIQUE INDEX "STG01"."SYS_C0031332" ON "STG01"."USERS" ("USERNAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "T_STG01" ;
;