/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddaxJob: typeof import('./../components/table/AddaxJob.vue')['default']
    AddaxLogList: typeof import('./../components/logs/AddaxLogList.vue')['default']
    AddaxResult: typeof import('./../components/table/AddaxResult.vue')['default']
    AddSource: typeof import('./../components/source/AddSource.vue')['default']
    AppBreadcrumb: typeof import('./../components/AppBreadcrumb.vue')['default']
    AppRegister: typeof import('./../components/AppRegister.vue')['default']
    AppVersion: typeof import('./../components/AppVersion.vue')['default']
    BatchAdd: typeof import('./../components/table/BatchAdd.vue')['default']
    BatchUpdate: typeof import('./../components/table/BatchUpdate.vue')['default']
    CleanupDialog: typeof import('./../components/logs/CleanupDialog.vue')['default']
    DialogComp: typeof import('./../components/table/DialogComp.vue')['default']
    FieldsCompare: typeof import('./../components/table/FieldsCompare.vue')['default']
    L5TEtlDataBar: typeof import('./../components/dashboard/L5TEtlDataBar.vue')['default']
    L5TEtlTimeBar: typeof import('./../components/dashboard/L5TEtlTimeBar.vue')['default']
    LineChart: typeof import('./../components/dashboard/LineChart.vue')['default']
    LogFiles: typeof import('./../components/table/LogFiles.vue')['default']
    LogModal: typeof import('./../components/table/LogModal.vue')['default']
    NavbarThemeSwitcher: typeof import('./../components/NavbarThemeSwitcher.vue')['default']
    Notifier: typeof import('./../components/Notifier.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableDetail: typeof import('./../components/table/TableDetail.vue')['default']
    TaskEtlProgress: typeof import('./../components/task/TaskEtlProgress.vue')['default']
    TaskList: typeof import('./../components/task/TaskList.vue')['default']
  }
}

// For TSX support
declare global {
  const AddaxJob: typeof import('./../components/table/AddaxJob.vue')['default']
  const AddaxLogList: typeof import('./../components/logs/AddaxLogList.vue')['default']
  const AddaxResult: typeof import('./../components/table/AddaxResult.vue')['default']
  const AddSource: typeof import('./../components/source/AddSource.vue')['default']
  const AppBreadcrumb: typeof import('./../components/AppBreadcrumb.vue')['default']
  const AppRegister: typeof import('./../components/AppRegister.vue')['default']
  const AppVersion: typeof import('./../components/AppVersion.vue')['default']
  const BatchAdd: typeof import('./../components/table/BatchAdd.vue')['default']
  const BatchUpdate: typeof import('./../components/table/BatchUpdate.vue')['default']
  const CleanupDialog: typeof import('./../components/logs/CleanupDialog.vue')['default']
  const DialogComp: typeof import('./../components/table/DialogComp.vue')['default']
  const FieldsCompare: typeof import('./../components/table/FieldsCompare.vue')['default']
  const L5TEtlDataBar: typeof import('./../components/dashboard/L5TEtlDataBar.vue')['default']
  const L5TEtlTimeBar: typeof import('./../components/dashboard/L5TEtlTimeBar.vue')['default']
  const LineChart: typeof import('./../components/dashboard/LineChart.vue')['default']
  const LogFiles: typeof import('./../components/table/LogFiles.vue')['default']
  const LogModal: typeof import('./../components/table/LogModal.vue')['default']
  const NavbarThemeSwitcher: typeof import('./../components/NavbarThemeSwitcher.vue')['default']
  const Notifier: typeof import('./../components/Notifier.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TableDetail: typeof import('./../components/table/TableDetail.vue')['default']
  const TaskEtlProgress: typeof import('./../components/task/TaskEtlProgress.vue')['default']
  const TaskList: typeof import('./../components/task/TaskList.vue')['default']
}